### ISSUE TITLE
Build issues on github actions 

### ISSUE THREAD

**Issue by rahulbagal** [Ryank90/action-hugo-firebase-deploy#3]
I am trying to setup CI for the first time on my hugo / firebase setup 

on push I see the below error on GitHub actions and the build is failing 

```
Warning: Unexpected input(s) 'alias', valid inputs are ['entryPoint', 'args', 'firebase-token', 'hugo-params']
Run ryank90/action-hugo-firebase-deploy@master
/usr/bin/docker run --name a5c76be40bf4b7c60f4f6e9aeb81f9bd4bfd11_9fb038 --label a5c76b --workdir /github/workspace --rm -e "INPUT_FIREBASE-TOKEN" -e "INPUT_ALIAS" -e "INPUT_HUGO-PARAMS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/jathinfo/jathinfo":"/github/workspace" a5c76b:e40bf4b7c60f4f6e9aeb81f9bd4bfd11  "***
" "***" "-D"
hugo v0.109.0-47b1[2](https://github.com/rahulbagal/jathinfo/actions/runs/4336750477/jobs/7572265321#step:4:2)b[8](https://github.com/rahulbagal/jathinfo/actions/runs/4336750477/jobs/7572265321#step:4:9)3e636224e5e601813ff3e67[9](https://github.com/rahulbagal/jathinfo/actions/runs/4336750477/jobs/7572265321#step:4:10)0c191e371+extended linux/amd64 BuildDate=2022-12-23T[10](https://github.com/rahulbagal/jathinfo/actions/runs/4336750477/jobs/7572265321#step:4:11):38:[11](https://github.com/rahulbagal/jathinfo/actions/runs/4336750477/jobs/7572265321#step:4:12)Z VendorInfo=gohugoio
Start building sites …
```

my github workflow file looks like 

```
on: [push]
name: Deploy Hugo to Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: ryank90/action-hugo-firebase-deploy@master
      with:
        firebase-token: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        alias: ${{ secrets.PROJECTID }}
        hugo-params: -D
```

Can you please check?
